<?php
$title = 'Fiangonana';
$pageStyle = 'visitor-style.css';
ob_start();
?>
<section id="banner" class="major">
    <div class="inner">
        <header class="major">
            <h1>Ny mpiangona</h1>
        </header>
        <div class="content">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas, fuga animi. Excepturi perspiciatis quas maxime odit molestias corporis consequuntur laboriosam cum minus ut magnam dicta ullam id quam, nesciunt totam!</p>
        </div>
    </div>
</section>
<main>
    <article class="py-5">
        <div class="container">
            <h1 class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe fuga aperiam aut quaerat quisquam veritatis ab debitis dicta delectus, qui error veniam adipisci laboriosam ad alias neque corrupti, deleniti exercitationem!</h1>
            <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora rem nulla vitae ipsum, iste minima repellendus sunt vero ad delectus quas voluptatum odio nesciunt accusamus esse recusandae perspiciatis ullam sequi voluptatibus quae adipisci? Fuga veniam libero labore placeat at. Officiis beatae itaque, quia impedit sunt ad tempore doloribus recusandae, velit aut corrupti at provident repudiandae veniam earum aspernatur incidunt voluptatibus tempora omnis quas quae necessitatibus. Voluptates aperiam optio, officiis ex numquam minus deserunt vero quasi recusandae ullam delectus facere? Sed laboriosam dignissimos, distinctio facilis illo iusto doloribus quaerat corrupti, exercitationem animi libero voluptas nulla accusantium odit magni omnis. Iusto sit enim reprehenderit velit debitis repellendus, inventore quia recusandae molestias eos maiores itaque. Dolorem tempore in fugit magni autem sit eligendi quas ipsam, atque porro iure quidem quo, libero tempora nemo!</p>
            <p class="mb-4">Aliquam deleniti quisquam nostrum quae accusantium! Repudiandae voluptate veniam non recusandae ipsam omnis asperiores in quo. Commodi suscipit nemo natus debitis, vitae earum, dolores architecto maiores aspernatur sequi voluptas beatae, fugit repudiandae. Corrupti omnis doloremque ducimus neque eos, ipsum totam amet, voluptas distinctio quam repellendus soluta veritatis numquam, in deleniti repellat exercitationem! Rem cupiditate molestias facilis aut, consequatur explicabo qui. Eveniet delectus, consequuntur ut laudantium itaque sapiente beatae qui iusto error. Neque eligendi culpa accusamus ducimus! Perferendis, ullam tempora nisi quisquam aperiam similique, beatae voluptates ut suscipit ipsam amet facere labore neque doloremque sunt cum praesentium nostrum recusandae, velit dolorem aliquid fugit! Velit eos modi vel culpa, laboriosam architecto voluptate, consequatur expedita doloribus mollitia ipsum. Reprehenderit soluta eius, nemo ab ut eum dolorem magni quo fugiat ipsa perferendis, culpa inventore!</p>
            <p class="mb-4">Labore fuga suscipit in esse doloribus, dolor iusto nobis. Exercitationem voluptate fuga sequi numquam beatae eaque consectetur ad assumenda, omnis aspernatur perferendis repudiandae atque modi amet soluta aut sit nesciunt deleniti, maxime, commodi culpa quae! Ab necessitatibus deleniti rem corrupti possimus, dicta excepturi fugit dolores ut vero eos consequatur soluta, porro quibusdam dignissimos quos ex nihil? Repellat corporis recusandae temporibus cum saepe cupiditate est necessitatibus dignissimos veniam. Rerum quam nam consequatur facere, culpa consectetur delectus aliquam voluptas, laudantium iste ex. Sequi, aliquid, perferendis aliquam, vitae reprehenderit ipsum consequatur pariatur autem assumenda incidunt quidem possimus. Cupiditate officia earum natus quasi quis id cumque optio? Recusandae esse itaque, deleniti, nobis suscipit explicabo molestiae eum harum numquam omnis qui fugit iste, quisquam facere ab sapiente neque necessitatibus. Eaque dignissimos facere enim obcaecati vero.</p>
            <h2 class="mb-4">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum incidunt molestias eius debitis quaerat natus animi, quibusdam quae sapiente, deleniti ut dolorum voluptate voluptates libero autem! Cupiditate sint vitae magni!</h2>
            <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque harum tempora delectus, eveniet dicta, ipsum aut quasi suscipit ad id corporis eius esse ut minus illum consequuntur quod quaerat. Corrupti libero quae quos tempore enim necessitatibus atque quisquam eius, cupiditate, ipsum, dicta repellat architecto repellendus natus nulla deserunt quasi pariatur debitis. Ut sint repellat ex iure aperiam unde! Nobis, nisi voluptatem? Soluta cum, ad quas sit molestias aut? Officiis labore, quam ad excepturi a voluptates beatae aspernatur asperiores sunt vero pariatur quo dolor atque ratione minus, eveniet impedit magnam cum dignissimos repudiandae? Quaerat aspernatur harum cumque, labore eligendi ipsum cum officiis perferendis impedit ipsa debitis nisi aperiam blanditiis fugit quam suscipit provident temporibus veniam veritatis esse! Ipsa quibusdam quas aliquid, error sed deserunt repudiandae corporis veniam. Blanditiis praesentium veritatis molestiae!</p>
            <p class="mb-4">Quidem delectus iste officia eos ducimus reiciendis quasi possimus magnam error dolor illum non explicabo deserunt consectetur quaerat quam, fugit tempore quod cumque voluptates itaque est mollitia. Ipsam ipsa iusto incidunt. Ab consectetur, molestias quisquam vitae temporibus repellendus dolor hic deleniti repudiandae itaque, corrupti, tenetur eum totam accusantium ad impedit numquam! Quisquam delectus laborum neque cum eveniet similique consectetur ipsam rerum, in perspiciatis ab a nulla aspernatur ea quibusdam sed enim magni dolor voluptates libero odio, quod modi est eaque! Rerum libero voluptatem repellendus placeat iste quia vero iure dolore asperiores! Itaque cumque modi nemo quidem voluptates corporis voluptatum iusto non quos odio incidunt quisquam commodi consectetur, vitae excepturi, ipsa ab eum amet? Maiores autem deleniti ut sint placeat eum qui, porro iure dolores tenetur. Officia neque ipsam repellat ex.</p>
            <p class="mb-4">Animi reiciendis inventore quaerat nostrum consectetur modi ad quod? Obcaecati aperiam dolor nihil deserunt, nam expedita placeat dignissimos iure ipsam delectus. Est amet, commodi sint laudantium voluptatibus vero minus numquam neque debitis, provident quo quidem molestiae pariatur aspernatur nobis non temporibus officiis dolore ipsam ab iusto dolores explicabo repellat. Dolor tempora harum aliquam laborum fugit nesciunt, similique deleniti quas nisi delectus itaque facere quisquam alias? Recusandae voluptates quae eius. Suscipit, animi fugiat iure soluta perferendis inventore quidem laboriosam nobis asperiores harum nesciunt a veritatis deleniti consectetur, quia at magnam error, incidunt blanditiis assumenda laudantium? Error, ducimus maxime. Mollitia fuga ipsam obcaecati nulla consectetur impedit maxime dolorem. Provident, obcaecati officiis! Id dolor dolore molestias facilis, numquam unde facere dolorum dignissimos obcaecati illo delectus sint rerum accusantium asperiores ex consequuntur soluta. Voluptatem?</p>
            <p class="mb-4">Commodi, provident. Distinctio impedit accusamus doloribus soluta fugit odio rem, quia quidem aut ducimus non odit repellat omnis temporibus rerum ut perspiciatis ullam exercitationem velit earum eum. Suscipit cupiditate pariatur sed architecto reiciendis. Maxime iure delectus reprehenderit. Commodi fugit adipisci odio tenetur, eos ab alias qui error quidem sunt suscipit sapiente voluptatum, tempore modi nobis sequi totam, aspernatur dicta sint. Assumenda aperiam, laboriosam dolorem repellat nostrum impedit illo. Impedit eaque aliquid reiciendis. Quaerat ea officiis eveniet tenetur? Explicabo, dolores. Eaque unde iusto doloribus, illo earum fuga consequatur tenetur quis, voluptatibus, commodi rem esse. Dicta obcaecati quam porro nostrum quo quis magnam excepturi amet maiores. Sint dolorum amet ipsa, quam sed alias est nobis quos corporis quia nemo neque voluptate libero? Nihil nam, quod quis laudantium vitae officiis recusandae? Optio, natus.</p>
        </div>
    </article>
</main>

<?php
$pageContent = ob_get_clean();
require_once dirname(__DIR__) . DIRECTORY_SEPARATOR . 'layouts' . DIRECTORY_SEPARATOR . 'baseOfViews.php';
