<?php
ob_start();
?>
<main>
    <div class="container">
        <article class="py-5">

            <h1><?= (isset($role) && !empty($role)) ? ($role) : 'Navigator' ; ?>'s views</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci nobis, perspiciatis sapiente excepturi esse dolore ipsam numquam voluptas voluptatum facere blanditiis accusamus, asperiores vitae amet molestiae temporibus! Tempore, mollitia. Nobis, nemo nostrum modi labore aperiam eius, libero asperiores pariatur repellendus assumenda sint totam reprehenderit unde necessitatibus veritatis mollitia numquam velit vel natus fugit? Quisquam corporis, tenetur quos voluptate hic necessitatibus, illo soluta minus commodi fugiat non rem, doloribus magnam voluptatem sint quae! Cumque perferendis aliquid tenetur fugiat enim, modi voluptas non eum? Cumque tenetur soluta sunt quos corrupti atque earum omnis labore, vel impedit libero repudiandae minima iusto fugit amet mollitia maxime adipisci nam. Distinctio sequi sit nostrum repellendus suscipit asperiores repudiandae illo odio et voluptate. Corrupti dolorum ad, quo fugit animi consectetur, quibusdam optio non, voluptates iste aliquam! Magni sint necessitatibus accusamus ipsa amet! Temporibus harum similique eaque unde mollitia incidunt dolorem et, provident ea rem sequi accusantium beatae, laborum itaque labore esse quis modi adipisci! Fugit libero sapiente doloribus eligendi quae nihil doloremque non nobis. Ducimus, ratione quidem quis nulla ex minima architecto beatae voluptas cum voluptatibus veritatis voluptates, mollitia, incidunt et. Ad sint blanditiis harum? Exercitationem praesentium corrupti omnis laborum unde reiciendis. Repellat obcaecati laudantium recusandae tenetur.</p>
            <p>Nobis, explicabo aliquam praesentium ducimus provident non ad autem laborum cupiditate numquam beatae dignissimos? Maxime ullam doloremque aspernatur nostrum, sapiente debitis quisquam repellat ea aliquam asperiores dolore, commodi aperiam voluptatem vel. Ad dolores cum minus repudiandae hic minima obcaecati. Fugiat reprehenderit tenetur esse similique cum vel quibusdam neque, quisquam iusto dicta eius exercitationem soluta hic quia. Totam eaque architecto explicabo consectetur, iure dolorum voluptate, ab, tempore ad autem cum omnis aspernatur quia neque suscipit obcaecati magni. Fugiat, unde quisquam earum temporibus ipsa rerum quam delectus dolore nesciunt repellendus blanditiis consequatur adipisci quasi nostrum, quidem sapiente corporis omnis, natus minima culpa. Adipisci neque itaque magnam unde vel, nesciunt quasi dicta totam at aspernatur eaque iste ducimus accusamus ratione, eos non ea dolore amet enim distinctio delectus eligendi! Commodi est perspiciatis veritatis eius hic enim? Fugiat, at cum suscipit maiores consequatur dignissimos repudiandae laudantium? Earum sit ab similique quas! Ratione nam molestias sunt rerum consequuntur optio earum adipisci blanditiis? Porro tempora sunt ea dolorum debitis excepturi minus laborum ex. Hic qui sed voluptas exercitationem rerum ipsam neque libero doloribus ab consectetur cupiditate id alias nostrum, nam suscipit quidem magni molestias dolorem, laboriosam sunt provident necessitatibus sint. Mollitia quasi ipsam eos officia repellat.</p>
            <p>Labore, rem maxime nam ducimus similique soluta id quaerat illo veritatis voluptatem ipsum, error hic itaque pariatur, fuga unde vel aliquid? Veniam quibusdam placeat ducimus magnam accusamus nulla. Optio deserunt, ab ut voluptatem quidem ipsum omnis quo quos minus rerum reprehenderit dignissimos delectus assumenda commodi doloremque totam veritatis vero esse eos, iure accusantium voluptas fugiat inventore modi? Totam, corrupti, quasi libero officiis qui cumque laudantium repellendus consequuntur nam deleniti magni quam tenetur suscipit similique, ex incidunt velit fuga dolores molestias fugiat soluta ad veniam labore inventore. Quos optio veniam, repellat alias unde totam sint necessitatibus quod, rem obcaecati molestias tempora, doloribus inventore! Error quibusdam nihil esse quo. Ducimus, sequi maxime unde officia ipsum, itaque est perspiciatis vitae ad id sit a temporibus laboriosam asperiores vero officiis earum dolore! Facere necessitatibus quod doloremque nostrum exercitationem non maiores ea vero sed numquam aspernatur suscipit, animi nobis alias, pariatur blanditiis omnis perspiciatis. Sit rem tenetur quisquam animi quis sequi minima fugit! Obcaecati quam animi rem nesciunt iusto ipsam praesentium quos natus, quis, reprehenderit rerum ducimus veritatis? Fuga sit saepe quod eius temporibus, recusandae doloremque asperiores, iste suscipit odit sint beatae accusantium illo enim dolore tenetur. Consequuntur explicabo vero dolorem laudantium voluptas reiciendis ea!</p>
            <p>Accusamus exercitationem rerum optio provident ullam culpa suscipit enim porro praesentium! Ab quam laborum fugiat repellendus labore repellat est suscipit nemo sint qui, commodi sequi dolor aspernatur natus non accusamus in voluptate ipsa delectus pariatur ipsum accusantium. Neque iste doloribus, accusamus totam voluptate, amet id dignissimos excepturi ipsa placeat praesentium quaerat in nisi molestias porro, eaque quidem iusto harum illum! Dolorem veritatis itaque adipisci laboriosam harum corporis rem, aspernatur explicabo provident tempore cum blanditiis consequuntur voluptatem tempora eius, beatae possimus nesciunt nihil vero enim porro voluptatibus magnam ea sed! Praesentium, veritatis architecto eos assumenda pariatur dolor aspernatur quidem velit ipsam ab nam possimus eius optio. Cum deserunt voluptate laborum! Quo blanditiis voluptates vitae placeat ut odit dolorum, sint labore quia cum, modi vero, natus iure harum similique consectetur aliquam pariatur. Ea quidem natus sapiente nesciunt atque dolor cupiditate esse sint aliquid autem eum, obcaecati laudantium at ratione nobis soluta, doloremque quo unde eligendi explicabo harum eveniet ipsa distinctio voluptate. Quia fuga repudiandae natus iusto pariatur adipisci, vero quam sapiente laborum odit suscipit excepturi qui incidunt odio quos unde nulla ducimus animi mollitia nobis perspiciatis dolor minus eos minima. Libero explicabo incidunt quae porro. Explicabo corporis natus ducimus obcaecati optio repellat?</p>
            <p>Sit modi reprehenderit ad culpa nihil, autem iusto quibusdam enim odio sapiente, voluptas quos sint voluptatum! Illum doloremque, incidunt quo vitae earum soluta error quaerat corrupti at eligendi expedita? Perferendis voluptas accusantium, qui ex inventore libero officia, fugiat debitis, eligendi tempora pariatur reprehenderit minus commodi? Officiis corrupti suscipit id debitis, quibusdam enim rem? Dolorem dolore ipsum ipsam, tempore adipisci quas incidunt id, corrupti, consequuntur amet minus veniam natus? Eos praesentium cupiditate recusandae adipisci officiis. Aliquid maiores odio dolores voluptates est doloribus sunt, ea adipisci eaque, laboriosam quasi doloremque omnis accusantium explicabo pariatur officia eos similique alias quibusdam exercitationem autem deserunt, beatae magnam! Eaque corrupti quasi quos! Perspiciatis fuga eius id quod iure nam atque at quibusdam commodi accusantium ea reiciendis hic facere, maxime quidem labore facilis quae ipsum distinctio nostrum architecto eum quos! Animi ut ipsum totam, minima at quae, nam eum dignissimos natus vel facere, minus cupiditate recusandae doloremque numquam alias temporibus excepturi possimus assumenda quisquam beatae pariatur magni maxime aliquam! Animi, numquam! Magni fugit aliquam ratione minima quia, nihil dolores suscipit dolorum totam. Nesciunt hic, magni, amet et, eos omnis debitis non obcaecati in pariatur ea atque molestiae qui quod mollitia iure sit incidunt accusantium? Eius, dolor quia.</p>
        </article>
    </div>
</main>
<?php
$pageContent = ob_get_clean();
$title = 'Profil';
?>

<?php
    require_once str_replace(['/', '..'], [DIRECTORY_SEPARATOR, dirname(__DIR__)], '../layouts/baseOfViews.php');
?>